apiVersion: skaffold/v1
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/bhborkar91/golang-rest
      context: .
      docker:
        dockerfile: Dockerfile
