name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login ghcr.io --username bhborkar91 --password "${{ secrets.GITHUB_TOKEN }}"
      - name: Build the Docker image
        run: docker-compose -f docker-compose.yml -f docker-compose.build.yml build
      - name: Push the Docker image
        run: docker-compose push app
        if: success()
      - name: Upload docker compose
        uses: actions/upload-artifact@v2.3.1
        if: success()
        with:
          # Artifact name
          name: docker-compose
          # A file, directory or wildcard pattern that describes what to upload
          path: docker-compose.yml
          # The desired behavior if no files are found using the provided path.
      - name: Upload kubernetes
        uses: actions/upload-artifact@v2.3.1
        if: success()
        with:
          # Artifact name
          name: k8s
          # A file, directory or wildcard pattern that describes what to upload
          path: infra/k8s
          # The desired behavior if no files are found using the provided path.


  deploy-docker:
    needs: build
    runs-on: deployment-box
    concurrency: 
      group: production
      cancel-in-progress: true
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          # Artifact name
          name: docker-compose
          # Destination path
          path: .

      - name: Pull latest images
        run: docker-compose pull
      - name: Deploy the containers
        run: docker-compose up -d
  deploy-k8s:
    needs: build
    runs-on: deployment-box
    concurrency: 
      group: production
      cancel-in-progress: true
    
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          # Artifact name
          name: k8s
          # Destination path
          path: .

      - name: Deploy the containers
        run: kubectl apply -f k8s/
