name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u bhborkar91 --password-stdin
    - name: Build the Docker image
      run: docker-compose build
